### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by Rothschear** [ShadowWhisperer/BlockLists#102]
https://ecosia.org and it's subdomains seem to be blocked. From what I know it's not a shady site.

**Comment by ShadowWhisperer** [comment]
Looks like it was blocked due to the extension being a potential search engine hijacker, and ad promoter.

_**2,105,973€** total income this month_ (Over 2.2 Million USD) from voluntary ad viewers/clickers, with a month that's only half way though.  Sounds sus, but over 2 million chrome downloads at ~2 USD per day.... maybe.

It does appear to be a legitimate company. Removed the following:

ecosia.com
ecosia.de
ecosia.org


Cheers!

https://howtoremove.guide/ecosia-org-virus-removal/
https://malwaretips.com/blogs/remove-ecosia-search/
https://support.google.com/chrome/thread/173085061/ecosia-has-browserjacked-me-%E2%80%94-how-to-fix?hl=en
https://www.2-spyware.com/remove-ecosia-org-virus.html
https://www.bugsfighter.com/remove-ecosia-org-windows-and-mac/
https://www.myantispyware.com/2017/06/21/how-to-remove-ecosia-org-chrome-firefox-ie-edge/
https://www.techsupportall.com/how-to-remove-ecosia-org-homepage-removal-help/
https://www.wipersoft.com/ecosia-org-how-to-remove/
