### ISSUE TITLE
location.services.mozilla.com

### ISSUE THREAD

**Issue by yoshimo** [ShadowWhisperer/BlockLists#110]
The Mozilla Location  Service is used to give you an estimated geographic location based on cell towers and wifi networks.
Personal Identifiable Information is not published. A privacy friendly approach to Googles version shouldn't be blocked.

**Comment by ShadowWhisperer** [comment]
A service that finds your location. It may/or may not send out personal information, but it is used for **finding your location**.  
  
  
**What Data MLS Collects**    
  
```
Information about the publicly observable Wi-Fi access points, cell towers and Bluetooth beacons closest to you. We may also determine your location from your device’s (e.g., computer, phone, tablet) IP address. You can prevent your Wi-Fi access points from being reported to Mozilla
  
Technical data like the time you made a location request and an approximation of how close you are to a Wi-Fi access point, cell tower, or Bluetooth beacon.
  
If MLS crashes, we receive information ***which may contain data that identifies you or is otherwise sensitive to you***  
  
MLS works on apps, websites, and services that are authorized to use MLS and that you have given permission to request your device’s location.
```
**which may contain data that identifies you or is otherwise sensitive to you**  
[SRC](https://location.services.mozilla.com/privacy)   
  
Service calls out even when location is turned off in both Firefox's settings, and "about:config".  


Going by [THIS](https://location.services.mozilla.com/optout), it sounds like your devices are logged, unless you opt-out.
