### ISSUE TITLE
RPZ Format For DNS SERVER Bind9 & Unbound

### ISSUE THREAD

**Issue by alsyundawy** [ShadowWhisperer/BlockLists#131]
Hai,

can you support RPZ Format For DNS SERVER Bind9 & Unbound?

**this example configuration for rpz bind9/unbound**

```
$TTL 300
@ SOA localhost. root.localhost. 1700434620 43200 3600 259200 300 
               NS  localhost.

domain.tld CNAME .
*.domain.tld CNAME .
name.tld CNAME .
*.name.tld CNAME .
```

**This example for Unbound**

```
server:
local-zone: "domain.tld." always_nxdomain
local-zone: "named.tld." always_nxdomain
```

**Comment by spirillen** [comment]
Just to mention... then the NS record is not stickily needed for RPZ zone files.

and to do it as you shows in your example, requires the source to be separated as I do in https://github.com/mypdns/matrix/tree/master/source/tracking, otherwise you will end up blacklisting sub-domains that should never have been blacklisted.

**Comment by ShadowWhisperer** [comment]
Hi,

I have no plans of supporting anything, other than a hosts file.
I may consider it in the future, if there is more demand.

- Sean
