### ISSUE TITLE
*.client-channel.google.com

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#27]
If I remember this one right, then this is for login + access to some of there storage and when you block them, I recalls it as you can't log in.

Just a 1 cent 

https://github.com/ShadowWhisperer/BlockLists/blob/d9e455b33aa2a344227276defafe8eec9152ba64/Testing/Unknown#L322-L352

Note to self: When this one is solved, update https://mypdns.org/my-privacy-dns/matrix/-/issues/1836

**Comment by ShadowWhisperer** [comment]
I thought so as well. Sometime I remember seeing it in the past, when not using Google Drive, or Google Keep. I just fired up a VM and messed with Google Drive for a while, and it doesn't call out to any  *.client-channel.google.com domains.

I have all DNS queries re-routed through a different VM using iptables. All DNS over TLS is blocked, from what I gather. Google's DNS is blocked. Everything seems to work find on both the web interface and the desktop application, including sync. and sign-in. I tried multiple different file types.
 
 Everything I have in the _BlockLists/Testing/Unknown_ folder, I have blocked on both my home network, and my work network.
 
These have me stumped... :confused:
Unless they are not used anymore ?

**Comment by spirillen** [comment]
This is like hearing my self think :smile: But where did you obtain these records? and when?

**Comment by ShadowWhisperer** [comment]
I'm not sure. I stated my block lists, probably 5 or 6 years ago. I didn't start sharing them, until ~2 years ago. I didn't start sharing the testing folder, until a few months ago. I debated about even posting it, but figured other users could see my thoughts, if they were looking a domain up.

When I started this, I wanted a way to block dating, and porn sites, due to several customer who kept bringing laptops into my shop and opening porn (on dating sites) when I had other customers in. I started observing the other traffic and my lists grew from there.

Initially I only blocked domains that came across my network, and now I used multiple top million lists to build a "source" lists to which I "scan" for information. The code below is an example of what I look for. Everything I know about programing is self tough, so I'm sure its messy. :zany_face: I went to college (10 years ago) for network security, and nobody even mentioned DNS...

```
#GoatStats
if [[ -n "$(grep -E '^analytics\.|^stats\.|^stat\.|^counter\.|^goat\.' <<< "$Site")" ]]; then
Info="$(timeout -s KILL 5 curl -sA "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/89.0" "https://$Site/count.js")"
if [[ "$(grep -ic 'goatcounter' <<< "$Info")" -gt '5' ]]; then echo "$Site" >> /root/Results/Tracker; Found='1'; return; fi; fi
```

**Comment by ShadowWhisperer** [comment]
I'm guessing these domains are no longer used. I'm going to delete them, to close the issue.

**Comment by spirillen** [comment]
Your might be right, dod some quick search on the domain and nothing really showed up.
