### ISSUE TITLE
possibility to create a hosts?

### ISSUE THREAD

**Issue by gallegonovato** [ShadowWhisperer/BlockLists#58]
Good afternoon:

First of all thank you for your work and effort.

I would like to ask you a question if I may.

I do not know if it would be possible to create a hosts file, with 0.0.0.0.0 of your lists.

Thank you very much for your time and help.

Best regards

**Comment by ShadowWhisperer** [comment]
Hi!

It's possible, but due to the size of the lists, I think it would bring your system to a crawl. 

I'd recommend setting up a dedicated computer (or even a virtual machine) to resolve DNS requests. Hosts file also doesn't do wildcard blocking.  

[NoTrack](https://quidsup.net/notrack/)
[PiHole](https://pi-hole.net/)
[DnsMasq](https://www.tecmint.com/setup-a-dns-dhcp-server-using-dnsmasq-on-centos-rhel/)  

If you're using Linux, you can run this command for the lists you want, using the RAW folder.  
` curl -s https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/RAW/Malware | sed -e 's/^/0.0.0.0 /' >> hostfile`  

Thanks for the nice comments!
- Sean

**Comment by spirillen** [comment]
Just to be the pain in the a... there is also Bind and PowerDNS's recursor, which both supports the RPZ (Response Policy Zone) system in full.

The last mentioned ([pdns-recursor](https://www.powerdns.com/recursor.html)) do also read in hosts formatted files which dosn't need to be the default [system hosts file](https://docs.powerdns.com/recursor/settings.html?highlight=hosts#etc-hosts-file)

For those Who might feel like trying the recursor with RPZ files, I have made a small getting started setup here ([Backup](https://github.com/DNS-RPZ/dns-rpz-integration/tree/master/PowerDNS-Recursor))
